### ISSUE TITLE
Adding resource endpoint

### ISSUE THREAD

**Issue by atakanyenel** [twharmon/goweb#61]
Hey,

I have this idea of adding `app.Resource("todo",ResourceInterface)` so that a endpoint will have CRUD automatically. It's just adding an interface with the endpoints get,post,delete, put and creating a method in engine.

What do you think ? If you are okay with it , I want to implement it myself  in a couple of days.

**Comment by twharmon** [comment]
@atakanyenel Feel free to make a PR.
